/**
 * Heroes, portfolio spreads, and gallery order per discipline.
 * Import ranks by resolution: slide-01 is strongest, then slide-02…
 */
const CURATED_PAGES = {
  murals: {
    cover: "slide-02",
    portfolio: ["slide-03", "slide-04", "gallery-01"],
    galleryPreview: ["slide-01", "slide-02", "slide-03", "gallery-01", "gallery-02", "gallery-03"],
    galleryOrder: [
      "slide-01",
      "slide-02",
      "slide-03",
      "slide-04",
      "gallery-01",
      "gallery-02",
      "gallery-03",
      "gallery-04",
      "gallery-05",
      "gallery-06",
      "gallery-07",
      "gallery-08",
      "gallery-09",
      "gallery-10",
      "gallery-11",
      "gallery-12",
    ],
    focal: { cover: "center 35%" },
    focus: {},
  },
  fauxFinishes: {
    cover: "slide-02",
    portfolio: ["slide-03", "slide-04", "gallery-01"],
    galleryPreview: ["slide-01", "slide-02", "slide-03", "gallery-01", "gallery-02", "gallery-03"],
    galleryOrder: [
      "slide-01",
      "slide-02",
      "slide-03",
      "slide-04",
      "gallery-01",
      "gallery-02",
      "gallery-03",
      "gallery-04",
      "gallery-05",
      "gallery-06",
      "gallery-07",
      "gallery-08",
      "gallery-09",
      "gallery-10",
      "gallery-11",
      "gallery-12",
    ],
    focal: { cover: "center 38%" },
    focus: {},
  },
  basRelief: {
    cover: "slide-02",
    portfolio: ["slide-01", "slide-03", "gallery-01"],
    galleryPreview: ["slide-01", "slide-02", "slide-03", "gallery-01", "gallery-02", "slide-04"],
    galleryOrder: [
      "slide-01",
      "slide-02",
      "slide-03",
      "slide-04",
      "gallery-01",
      "gallery-02",
      "gallery-03",
    ],
    focal: { cover: "center 35%" },
    focus: {},
  },
  cabinetFinishes: {
    cover: "slide-02",
    portfolio: ["slide-03", "slide-04", "gallery-01"],
    galleryPreview: ["slide-01", "slide-02", "slide-03", "gallery-01", "gallery-02", "gallery-03"],
    galleryOrder: [
      "slide-01",
      "slide-02",
      "slide-03",
      "slide-04",
      "gallery-01",
      "gallery-02",
      "gallery-03",
      "gallery-04",
      "gallery-05",
      "gallery-06",
      "gallery-07",
    ],
    focal: { cover: "center 40%" },
    focus: {},
  },
  ceilingsFloors: {
    cover: "slide-02",
    portfolio: ["slide-01", "slide-03", "gallery-01"],
    galleryPreview: ["slide-01", "slide-02", "slide-03", "gallery-01", "gallery-02", "gallery-03"],
    galleryOrder: [
      "slide-01",
      "slide-02",
      "slide-03",
      "slide-04",
      "gallery-01",
      "gallery-02",
      "gallery-03",
      "gallery-04",
      "gallery-05",
      "gallery-06",
      "gallery-07",
      "gallery-08",
    ],
    focal: { cover: "center 28%" },
    focus: {},
  },
  chinoiserie: {
    cover: "slide-02",
    portfolio: ["slide-01", "slide-03", "gallery-01"],
    galleryPreview: ["slide-01", "slide-02", "slide-03", "gallery-01", "gallery-02", "gallery-03"],
    galleryOrder: [
      "slide-01",
      "slide-02",
      "slide-03",
      "slide-04",
      "gallery-01",
      "gallery-02",
      "gallery-03",
      "gallery-04",
    ],
    focal: { cover: "center 36%" },
    focus: {},
  },
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { CURATED_PAGES };
}
