#!/usr/bin/env node
/**
 * Regenerate header + mobile nav on every page from js/site-config.js
 * Usage: node tools/sync-nav.js
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const { SITE_NAV, SITE_VERSION } = require(path.join(ROOT, "js", "site-config.js"));

const HEAD_SCRIPTS =
  `  <script src="js/site-config.js?v=${SITE_VERSION}"></script>\n` +
  `  <script src="js/site-nav.js?v=${SITE_VERSION}" defer></script>\n`;

function navBlock(activeHref) {
  const links = SITE_NAV.map(({ href, label }) => {
    const active = href === activeHref ? ' class="active"' : "";
    return `    <a href="${href}"${active}>${label}</a>`;
  }).join("\n");

  return `<header class="topbar">
  <a class="brand" href="index.html">Connie Harris</a>
  <div class="topbar-end">
    <button class="menu-btn" id="menu-btn" type="button" aria-label="Toggle menu" aria-expanded="false">Menu</button>
    <nav class="nav" aria-label="Primary">
${links}
    </nav>
  </div>
</header>
<div class="mobile-menu" id="mobile-menu">
${links}
</div>`;
}

const ACTIVE = Object.fromEntries(SITE_NAV.map((item) => [item.href, item.href]));

function cleanMarkup(text) {
  text = text.replace(/<script src="js\/site-config\.js[^>]*><\/script>/gi, "");
  text = text.replace(/<script src="js\/site-nav\.js[^>]*><\/script>/gi, "");
  text = text.replace(/<header class="topbar">[\s\S]*?<\/header>\s*/g, "");
  text = text.replace(/<div class="mobile-menu" id="mobile-menu">[\s\S]*?<\/div>\s*/g, "");
  text = text.replace(/\n<\/header>\s*\n<\/header>\s*/g, "\n");
  text = text.replace(
    /(<div class="mobile-menu" id="mobile-menu">[\s\S]*?<\/div>)\s*\n<\/header>\s*/g,
    "$1\n"
  );
  return text;
}

function syncFile(filePath) {
  const name = path.basename(filePath);
  const active = ACTIVE[name];
  if (!active) return false;

  let text = cleanMarkup(fs.readFileSync(filePath, "utf8"));

  const bodyMatch = text.match(/<body[^>]*>/);
  if (!bodyMatch) {
    console.log(`✗ no body tag: ${name}`);
    return false;
  }

  const insertAt = bodyMatch.index + bodyMatch[0].length;
  text = text.slice(0, insertAt) + "\n" + navBlock(active) + "\n" + text.slice(insertAt);
  text = text.replace("</head>", HEAD_SCRIPTS + "</head>");
  text = text.replace(/\?v=\d{8}[a-z]/g, `?v=${SITE_VERSION}`);

  fs.writeFileSync(filePath, text);
  console.log(`✓ ${name}`);
  return true;
}

/** Practice pages are generated by build-portfolio-pages.js — do not sync here. */
const STATIC_PAGES = ["index.html", "classes.html", "contact.html"];

STATIC_PAGES.forEach((f) => syncFile(path.join(ROOT, f)));
